webtalk_init -webtalk_dir /home/limuyang1999/Desktop/Computer Architecture Task 2/Riscv-cpu Project/Riscv-cpu Project.sim/sim_1/behav/xsim/xsim.dir/pc_reg_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jan  6 14:11:30 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018833" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "345e1a4c-b0a6-49c3-9491-94eb85fa699d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f6dc597a0d1c44a2b527dc557a7ac92b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu Bionic Beaver (development branch)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394.559 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "129392_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2603121770 -regid "" -xml /home/limuyang1999/Desktop/Computer Architecture Task 2/Riscv-cpu Project/Riscv-cpu Project.sim/sim_1/behav/xsim/xsim.dir/pc_reg_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/limuyang1999/Desktop/Computer Architecture Task 2/Riscv-cpu Project/Riscv-cpu Project.sim/sim_1/behav/xsim/xsim.dir/pc_reg_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/limuyang1999/Desktop/Computer Architecture Task 2/Riscv-cpu Project/Riscv-cpu Project.sim/sim_1/behav/xsim/xsim.dir/pc_reg_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
